apiVersion: v1
kind: Service
metadata:
  name: monitor
  namespace: ${k8s_ns}
  labels:
    app: monitor
spec:
  type: ClusterIP
  ports:
    - port: 21002
      targetPort: 21002
      protocol: TCP
      name: restful
  selector:
    app: monitor

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: monitor
  namespace: ${k8s_ns}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: monitor
  template:
    metadata:
      labels:
        name: monitor
        app: monitor
    spec:
      containers:
        - name: monitor
          image: ${docker_prefix}/monitor:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 21002
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "${spring_cloud_zookeeper_enabled}"
            - name: spring_cloud_zookeeper_connectString
              value: "${spring_cloud_zookeeper_connectString}"
            - name: spring_cloud_zookeeper_auth_info
              value: "${spring_cloud_zookeeper_auth_info}"
            - name: spring_cloud_zookeeper_auth_secky
              value: "${spring_cloud_zookeeper_auth_secky}"
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

