apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ${k8s_ns}
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: restful
  selector:
    app: gateway

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
  namespace: ${k8s_ns}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gateway
  template:
    metadata:
      labels:
        name: gateway
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ${docker_prefix}/gateway:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "${spring_cloud_zookeeper_enabled}"
            - name: spring_cloud_zookeeper_connectString
              value: "${spring_cloud_zookeeper_connectString}"
            - name: spring_cloud_zookeeper_auth_info
              value: "${spring_cloud_zookeeper_auth_info}"
            - name: spring_cloud_zookeeper_auth_secky
              value: "${spring_cloud_zookeeper_auth_secky}"
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

