apiVersion: v1
kind: Service
metadata:
  name: manage
  namespace: ${k8s_ns}
  labels:
    app: manage
spec:
  type: ClusterIP
  ports:
    - port: 21001
      targetPort: 21001
      protocol: TCP
      name: restful
  selector:
    app: manage

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: manage
  namespace: ${k8s_ns}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manage
  template:
    metadata:
      labels:
        name: manage
        app: manage
    spec:
      containers:
        - name: manage
          image: ${docker_prefix}/manage:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 21001
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "${spring_cloud_zookeeper_enabled}"
            - name: spring_cloud_zookeeper_connectString
              value: "${spring_cloud_zookeeper_connectString}"
            - name: spring_cloud_zookeeper_auth_info
              value: "${spring_cloud_zookeeper_auth_info}"
            - name: spring_cloud_zookeeper_auth_secky
              value: "${spring_cloud_zookeeper_auth_secky}"
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

