apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: ${k8s_ns}
  labels:
    app: config
spec:
  type: ClusterIP
  ports:
    - port: 21000
      targetPort: 21000
      protocol: TCP
      name: restful
  selector:
    app: config

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: config
  namespace: ${k8s_ns}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config
  template:
    metadata:
      labels:
        name: config
        app: config
    spec:
      containers:
        - name: config
          image: ${docker_prefix}/config:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 21000
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "${spring_cloud_zookeeper_enabled}"
            - name: spring_cloud_zookeeper_connectString
              value: "${spring_cloud_zookeeper_connectString}"
            - name: spring_cloud_zookeeper_auth_info
              value: "${spring_cloud_zookeeper_auth_info}"
            - name: spring_cloud_zookeeper_auth_secky
              value: "${spring_cloud_zookeeper_auth_secky}"
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

