apiVersion: v1
kind: Service
metadata:
  name: manage-ui
  namespace: ${k8s_ns}
  labels:
    app: manage-ui
spec:
  type: ClusterIP
  ports:
    - port: 21002
      targetPort: 21002
      protocol: TCP
      name: restful
  selector:
    app: manage-ui

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: manage-ui
  namespace: ${k8s_ns}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manage-ui
  template:
    metadata:
      labels:
        name: manage-ui
        app: manage-ui
    spec:
      containers:
        - name: manage-ui
          image: ${docker_prefix}/manage-ui:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 21002
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "${spring_cloud_zookeeper_enabled}"
            - name: spring_cloud_zookeeper_connectString
              value: "${spring_cloud_zookeeper_connectString}"
            - name: spring_cloud_zookeeper_auth_info
              value: "${spring_cloud_zookeeper_auth_info}"
            - name: spring_cloud_zookeeper_auth_secky
              value: "${spring_cloud_zookeeper_auth_secky}"
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

